name: CI-compile

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ["PSX=0 EE_BIN=PS2.ELF"] #PSX=1 EE_BIN=PSX.ELF", 
    container: ps2dev/ps2dev:v1.0
    # instead of "ps2dev/ps2dev:latest" you can use different tags, for example for old projects you can use "ps2dev/ps2dev:v1.0"
    steps:
      - name: Install dependencies
        run: |
          apk add build-base git zip

      - uses: actions/checkout@v2
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow

      - name: Get short SHA and repository name
        id: slug
        run: |
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
          echo "::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"

      - name: Compile osd
        run: |
          cd osd/loader
          make clean all
          cd ..
          make clean all ${{ matrix.type }}
          cd ..
          ls -l osd

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: BOOTLOADERS
          path: |
            osd/*.ELF


  build-kernelpatch:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    # instead of "ps2dev/ps2dev:latest" you can use different tags, for example for old projects you can use "ps2dev/ps2dev:v1.0"
    steps:
      - name: Install dependencies
        run: |
          apk add build-base git zip

      - uses: actions/checkout@v2
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow

      - name: Compile kpatch
        run: |
          make -C kpatch/patch0100
          make -C kpatch/patch0101
          ls -l kpatch/patch0100
          ls -l kpatch/patch0101

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          path: |
            kpatch/patch0100/osdsys.elf
            kpatch/patch0101/osd110.elf
